# Laboratorium 3 — NumPy
**Autor:** Natalia Ziółkowska

In [1]:
import numpy as np

In [2]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [4]:
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [7]:
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [8]:
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [9]:
print(f"shape: {losowe_oceny.shape}")

shape: (20,)


In [10]:
print(f"ndim: {losowe_oceny.ndim}")

ndim: 1


In [11]:
print(f"size: {losowe_oceny.size}")

size: 20


In [12]:
print(f"dtype: {losowe_oceny.dtype}")

dtype: int64


## Indeksowanie i slicing

In [14]:
import numpy as np 
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221]) 

In [15]:
print(f"Sprzedaż w styczniu: {miesiace_sprzedaz[0]}")

Sprzedaż w styczniu: 120


In [17]:
print(f"Sprzedaż w grudniu: {miesiace_sprzedaz[-1]}")

Sprzedaż w grudniu: 221


In [18]:
q1 = miesiace_sprzedaz[0:3]
print(f"Sprzedaż w Q1: {q1}")

Sprzedaż w Q1: [120 135  98]


In [19]:
q4 = miesiace_sprzedaz[-3:]
print(f"Sprzedaż w Q4: {q4}")

Sprzedaż w Q4: [143 198 221]


In [20]:
co_drugi = miesiace_sprzedaz[::2] 
print(f"Co drugi miesiąc: {co_drugi}")

Co drugi miesiąc: [120  98 167 201 156 198]


In [21]:
od_tylu = miesiace_sprzedaz[::-1] 
print(f"Sprzedaż od tyłu: {od_tylu}")

Sprzedaż od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


In [22]:

dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [23]:
wynik_b1 = dane[0, 1]
print(f"B1: {wynik_b1}")

B1: 145


In [26]:
wynik_b2 = dane[2]
print(f"B2: {wynik_b2}")

B2: [234 267 289]


In [27]:
wynik_b3 = dane[:,0]
print(f"B3: {wynik_b3}")

B3: [120  89 234  56]


In [28]:
wynik_b4 = dane[1:3,1:3]
print(f"B4: {wynik_b4}")

B4: [[102  95]
 [267 289]]


# Operacje wektorowe 

# Produkty w sklepie internetowym

In [39]:
nazwy = np.array(['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka'])
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [30]:
print(f"Średnia cena: {ceny.mean()} zł")

Średnia cena: 1171.0 zł


In [31]:
print(f"Najdroższy produkt (cena): {ceny.max()} zł")

Najdroższy produkt (cena): 3499 zł


In [32]:
print(f"Najtańszy produkt (cena): {ceny.min()} zł")

Najtańszy produkt (cena): 89 zł


In [33]:
wartosc_produktow = ceny * ilosci_magazyn
laczna_wartosc = wartosc_produktow.sum()
print(f"Łączna wartość magazynu: {laczna_wartosc} zł")

Łączna wartość magazynu: 549465 zł


In [34]:
ceny_rabat = ceny * 0.85  
ceny_vat = ceny * 1.23    
powyzej_1000 = (ceny > 1000).sum() 
print(f"Liczba produktów powyżej 1000 zł: {powyzej_1000}")

Liczba produktów powyżej 1000 zł: 4


In [40]:
maska_oceny = oceny_klientow >= 4.5
print("Produkty z wysoką oceną:")
print(f"Nazwy: {nazwy[maska_oceny]}") 
print(f"Ceny: {ceny[maska_oceny]}")

maska_tanie = ceny < 200 
print("\nProdukty poniżej 200 zł:")
print(f"Nazwy: {nazwy[maska_tanie]}")

Produkty z wysoką oceną:
Nazwy: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ceny: [3499 2499  349 1499]

Produkty poniżej 200 zł:
Nazwy: ['Ładowarka' 'Mysz']


In [42]:
maska_magazyn = ilosci_magazyn < 30 
print(f"Niski stan: {nazwy[maska_magazyn]}") 

wartosci = ceny * ilosci_magazyn 
wartosc_niskich = wartosci[maska_magazyn].sum() 
print(f"Łączna wartość tych produktów: {wartosc_niskich} zł")

suma_niskie = ilosci_magazyn[maska_magazyn].sum()
suma_wszystkie = ilosci_magazyn.sum()
procent = (suma_niskie / suma_wszystkie) * 100

print(f"Ilościowo produkty te stanowią {procent:.2f}% całego magazynu.")

Niski stan: ['Laptop' 'Monitor']
Łączna wartość tych produktów: 86962 zł
Ilościowo produkty te stanowią 3.82% całego magazynu.


In [43]:
maska_okazja = (oceny_klientow >= 4.5) & (ceny < 1000)
print(f"Produkty będące okazją: {nazwy[maska_okazja]}")
print(f"Ich ceny: {ceny[maska_okazja]} zł, oceny: {oceny_klientow[maska_okazja]}")


maska_dobra_ocena = oceny_klientow >= 4.0
maska_slaba_ocena = oceny_klientow < 4.0

srednia_dobra = ceny[maska_dobra_ocena].mean()
srednia_slaba = ceny[maska_slaba_ocena].mean()

print(f"\nŚrednia cena produktów z oceną >= 4.0: {srednia_dobra:.2f} zł")
print(f"Średnia cena produktów z oceną < 4.0: {srednia_slaba:.2f} zł")

Produkty będące okazją: ['Słuchawki']
Ich ceny: [349] zł, oceny: [4.8]

Średnia cena produktów z oceną >= 4.0: 1446.14 zł
Średnia cena produktów z oceną < 4.0: 529.00 zł


In [44]:
import time

In [45]:
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [46]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 73.3 ms
NumPy: 7.7 ms
NumPy jest 9× szybszy!


In [47]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 5.9 ms
NumPy: 0.6 ms
NumPy jest 9× szybszy!


In [48]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 30.7 ms
NumPy: 1.6 ms
NumPy jest 20× szybszy!


## Wnioski z benchmarku

- NumPy jest 9x szybszy w mnożeniu

- NumPy jest 9x szybszy w sumowaniu

- NumPy jest 20x szybszy w filtrowaniu

- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list

In [3]:
import numpy as np 
print(np.__version__)

2.4.3
