# Laboratorium 3 — NumPy
**Autor:** Natalia Ziółkowska

In [2]:
import numpy as np

In [3]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [4]:
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [7]:
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [8]:
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [9]:
print(f"shape: {losowe_oceny.shape}")

shape: (20,)


In [10]:
print(f"ndim: {losowe_oceny.ndim}")

ndim: 1


In [11]:
print(f"size: {losowe_oceny.size}")

size: 20


In [12]:
print(f"dtype: {losowe_oceny.dtype}")

dtype: int64


## Indeksowanie i slicing

In [14]:
import numpy as np 
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221]) 

In [15]:
print(f"Sprzedaż w styczniu: {miesiace_sprzedaz[0]}")

Sprzedaż w styczniu: 120


In [17]:
print(f"Sprzedaż w grudniu: {miesiace_sprzedaz[-1]}")

Sprzedaż w grudniu: 221


In [18]:
q1 = miesiace_sprzedaz[0:3]
print(f"Sprzedaż w Q1: {q1}")

Sprzedaż w Q1: [120 135  98]


In [19]:
q4 = miesiace_sprzedaz[-3:]
print(f"Sprzedaż w Q4: {q4}")

Sprzedaż w Q4: [143 198 221]


In [20]:
co_drugi = miesiace_sprzedaz[::2] 
print(f"Co drugi miesiąc: {co_drugi}")

Co drugi miesiąc: [120  98 167 201 156 198]


In [21]:
od_tylu = miesiace_sprzedaz[::-1] 
print(f"Sprzedaż od tyłu: {od_tylu}")

Sprzedaż od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


In [22]:

dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [23]:
wynik_b1 = dane[0, 1]
print(f"B1: {wynik_b1}")

B1: 145


In [26]:
wynik_b2 = dane[2]
print(f"B2: {wynik_b2}")

B2: [234 267 289]


In [27]:
wynik_b3 = dane[:,0]
print(f"B3: {wynik_b3}")

B3: [120  89 234  56]


In [28]:
wynik_b4 = dane[1:3,1:3]
print(f"B4: {wynik_b4}")

B4: [[102  95]
 [267 289]]


# Operacje wektorowe 

# Produkty w sklepie internetowym

In [39]:
nazwy = np.array(['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka'])
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [30]:
print(f"Średnia cena: {ceny.mean()} zł")

Średnia cena: 1171.0 zł


In [31]:
print(f"Najdroższy produkt (cena): {ceny.max()} zł")

Najdroższy produkt (cena): 3499 zł


In [32]:
print(f"Najtańszy produkt (cena): {ceny.min()} zł")

Najtańszy produkt (cena): 89 zł


In [33]:
wartosc_produktow = ceny * ilosci_magazyn
laczna_wartosc = wartosc_produktow.sum()
print(f"Łączna wartość magazynu: {laczna_wartosc} zł")

Łączna wartość magazynu: 549465 zł


In [34]:
ceny_rabat = ceny * 0.85  
ceny_vat = ceny * 1.23    
powyzej_1000 = (ceny > 1000).sum() 
print(f"Liczba produktów powyżej 1000 zł: {powyzej_1000}")

Liczba produktów powyżej 1000 zł: 4


In [40]:
maska_oceny = oceny_klientow >= 4.5
print("Produkty z wysoką oceną:")
print(f"Nazwy: {nazwy[maska_oceny]}") 
print(f"Ceny: {ceny[maska_oceny]}")

maska_tanie = ceny < 200 
print("\nProdukty poniżej 200 zł:")
print(f"Nazwy: {nazwy[maska_tanie]}")

Produkty z wysoką oceną:
Nazwy: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ceny: [3499 2499  349 1499]

Produkty poniżej 200 zł:
Nazwy: ['Ładowarka' 'Mysz']


In [42]:
maska_magazyn = ilosci_magazyn < 30 
print(f"Niski stan: {nazwy[maska_magazyn]}") 

wartosci = ceny * ilosci_magazyn 
wartosc_niskich = wartosci[maska_magazyn].sum() 
print(f"Łączna wartość tych produktów: {wartosc_niskich} zł")

suma_niskie = ilosci_magazyn[maska_magazyn].sum()
suma_wszystkie = ilosci_magazyn.sum()
procent = (suma_niskie / suma_wszystkie) * 100

print(f"Ilościowo produkty te stanowią {procent:.2f}% całego magazynu.")

Niski stan: ['Laptop' 'Monitor']
Łączna wartość tych produktów: 86962 zł
Ilościowo produkty te stanowią 3.82% całego magazynu.


In [43]:
maska_okazja = (oceny_klientow >= 4.5) & (ceny < 1000)
print(f"Produkty będące okazją: {nazwy[maska_okazja]}")
print(f"Ich ceny: {ceny[maska_okazja]} zł, oceny: {oceny_klientow[maska_okazja]}")


maska_dobra_ocena = oceny_klientow >= 4.0
maska_slaba_ocena = oceny_klientow < 4.0

srednia_dobra = ceny[maska_dobra_ocena].mean()
srednia_slaba = ceny[maska_slaba_ocena].mean()

print(f"\nŚrednia cena produktów z oceną >= 4.0: {srednia_dobra:.2f} zł")
print(f"Średnia cena produktów z oceną < 4.0: {srednia_slaba:.2f} zł")

Produkty będące okazją: ['Słuchawki']
Ich ceny: [349] zł, oceny: [4.8]

Średnia cena produktów z oceną >= 4.0: 1446.14 zł
Średnia cena produktów z oceną < 4.0: 529.00 zł


In [44]:
import time

In [45]:
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [46]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 73.3 ms
NumPy: 7.7 ms
NumPy jest 9× szybszy!


In [47]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 5.9 ms
NumPy: 0.6 ms
NumPy jest 9× szybszy!


In [48]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 30.7 ms
NumPy: 1.6 ms
NumPy jest 20× szybszy!


## Wnioski z benchmarku

- NumPy jest 9x szybszy w mnożeniu

- NumPy jest 9x szybszy w sumowaniu

- NumPy jest 20x szybszy w filtrowaniu

- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list

In [3]:
import numpy as np 
print(np.__version__)

2.4.3


# Ceny 4 produktów w 3 sklepach

In [6]:
ceny = np.array([[29.99, 31.99, 28.99],
[49.99, 52.99, 47.99], 
[14.99, 15.99, 13.99], 
[99.99, 104.99, 94.99]]) 
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")

Kształt macierzy: (4, 3)


# Zadanie 1a:

In [11]:
ceny_inflacja= ceny* 1.05
print (f'Ceny po inflacji: {ceny_inflacja}')

Ceny po inflacji: [[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


# Zadanie 1b

In [13]:
rabaty = np.array([0.10, 0.05, 0.15])
ceny_rabat= ceny * (1 - rabaty)

print(f'Ceny po rabacie: {ceny_rabat}')

Ceny po rabacie: [[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


## Zadanie 1c

In [8]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt_zakupu = ceny / (1 + marza)
print(f'Macierz kosztów zakupu (netto): {koszt_zakupu}')

Macierz kosztów zakupu (netto): [[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


## Zadanie 1d

In [9]:
sklepy = np.array(['Centrum', 'Galeria', 'Online'])
indeksy_min = ceny.argmin(axis=1)
produkty_nazwy = ['A', 'B', 'C', 'D']

for i in range(len(produkty_nazwy)):
    print(f'Produkt {produkty_nazwy[i]}: Najtańszy sklep to {sklepy[indeksy_min[i]]}')

Produkt A: Najtańszy sklep to Online
Produkt B: Najtańszy sklep to Online
Produkt C: Najtańszy sklep to Online
Produkt D: Najtańszy sklep to Online


## Ćwiczenie 2: Reshape i łączenie danych

# Zadanie 2a 

In [10]:
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


# Zadanie 2b — Stacking

In [11]:
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


# Zadanie 2c 

In [21]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
sprzedaz_macierz=sprzedaz_flat.reshape(6, 2)
print(f'Macierz sprzedaży :{sprzedaz_macierz}')

print(f'Średnia sprzedaz to:{sprzedaz_macierz.mean(axis=1)}')

roznica= sprzedaz_macierz[:, 1] - sprzedaz_macierz[:, 0]
print(f'Zmiana sprzedaży (M2 - M1): {roznica}')


Macierz sprzedaży :[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
Średnia sprzedaz to:[150. 225. 215. 170. 240. 225.]
Zmiana sprzedaży (M2 - M1): [100 150 -70 100 140 -70]


# Zadanie 2d

In [22]:
dane_wektor = kwartaly.flatten()
print(f'Dane po spłaszczeniu: {dane_wektor}')
nowy_miesiac = np.array([235])
dane_rozszerzone = np.concatenate([dane_wektor, nowy_miesiac])

print(f'Nowa długość tablicy: {len(dane_rozszerzone)}')

Dane po spłaszczeniu: [120 135  98 142 167 189 201 178 156 143 198 221]
Nowa długość tablicy: 13


# Ćwiczenie 3:

In [23]:
np.random.seed(2026)

In [24]:
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

# Zadanie 3a: Analiza wynagrodzeń

In [28]:
srednia = pensje.mean()
mediana = np.median(pensje)
std = pensje.std()

print(f'Średnia: {srednia} zł, Mediana: {mediana} zł, Odchylenie: {std:.2f} zł')

nazwy_np = np.array(pracownicy)
powyzej_sredniej = nazwy_np[pensje > srednia]
print(f'Powyżej średniej zarabiają: {powyzej_sredniej}')

ponizej_mediany = nazwy_np[pensje < mediana]
print(f'Poniżej mediany zarabiają: {ponizej_mediany}')

rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f'Rozstęp: {rozstep} zł, IQR: {iqr} zł')

Średnia: 6425.0 zł, Mediana: 6050.0 zł, Odchylenie: 1616.90 zł
Powyżej średniej zarabiają: ['Jan' 'Marek' 'Zofia']
Poniżej mediany zarabiają: ['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp: 4900 zł, IQR: 2200.0 zł


# Zadanie 3b:

In [45]:
warunki_premii = [
    oceny >= 4.5,
    (oceny >= 4.0) & (oceny < 4.5),
    oceny < 4.0
]
wartosci_premii = [2000, 1000, 0]

premie = np.select(warunki_premii, wartosci_premii, default=0) 
nowe_pensje = pensje + premie
print(f'Przyznane premie: {premie}')
print(f'Nowe wynagrodzenia całkowite: {nowe_wynagrodzenie}')

max_p = premie.max()
print(f'Osoby z najwyższą premią ({max_p} zł): {nazwy_np[premie == max_p]}')

Przyznane premie: [1000    0 2000 1000 2000    0 1000    0]
Nowe wynagrodzenia całkowite: [ 6500  7200  6800 10100  8300  4200  9500  5800]
Osoby z najwyższą premią (2000 zł): ['Ewa' 'Kasia']


# Zadanie 3c:

In [46]:
kolejnosc = np.argsort(pensje)[::-1]
print('Ranking pracowników (od najwyższych zarobków):')
for i, idx in enumerate(kolejnosc, 1):
    print(f'{i}. {pracownicy[idx]:<6} | Pensja: {pensje[idx]} zł | Staż: {staz[idx]} lat')

Ranking pracowników (od najwyższych zarobków):
1. Marek  | Pensja: 9100 zł | Staż: 15 lat
2. Zofia  | Pensja: 8500 zł | Staż: 12 lat
3. Jan    | Pensja: 7200 zł | Staż: 8 lat
4. Kasia  | Pensja: 6300 zł | Staż: 5 lat
5. Tomek  | Pensja: 5800 zł | Staż: 4 lat
6. Anna   | Pensja: 5500 zł | Staż: 3 lat
7. Ewa    | Pensja: 4800 zł | Staż: 2 lat
8. Piotr  | Pensja: 4200 zł | Staż: 1 lat


# Zadanie 3d:

In [35]:
kor_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
kor_staz_ocena = np.corrcoef(staz, oceny)[0, 1]
print(f'Korelacja staż-pensja: {kor_staz_pensja:.2f}')
print(f'Korelacja staż-ocena: {kor_staz_ocena:.2f}')

if abs(kor_staz_pensja) > abs(kor_staz_ocena):
    print('Silniejszy związek występuje między stażem a pensją.')
else:
    print('Silniejszy związek występuje między stażem a oceną.')

Korelacja staż-pensja: 0.99
Korelacja staż-ocena: 0.04
Silniejszy związek występuje między stażem a pensją.


# Zadanie 3e: 

In [36]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol
print(f'Macierz przychodu (produkty x miesiące): {przychod}')

produkt_idx = przychod.sum(axis=1).argmax()
print(f'Produkt z największym przychodem: {produkty_nazwy[produkt_idx]}')

miesiac_idx = przychod.sum(axis=0).argmax()
print(f'Najlepszy miesiąc (indeks): {miesiac_idx}')

trend_poczatek = przychod[:, :3].sum()
trend_koniec = przychod[:, 3:].sum()

print(f'Przychód Q1+Q2 (m-ce 0-2): {trend_poczatek} zł')
print(f'Przychód Q3+Q4 (m-ce 3-5): {trend_koniec} zł')

Macierz przychodu (produkty x miesiące): [[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
Produkt z największym przychodem: Smartfon
Najlepszy miesiąc (indeks): 1
Przychód Q1+Q2 (m-ce 0-2): 2463950 zł
Przychód Q3+Q4 (m-ce 3-5): 2536500 zł


## Ćwiczenie 4: Generowanie danych

In [37]:
np.random.seed(42)
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

In [41]:
print(f'Wiek - średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}') 
print(f'Wydatki - max: {wydatki.max():.2f}, min: {wydatki.min():.2f}') 

kor_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1] 
print(f'Korelacja wiek-wydatki: {kor_wiek_wydatki:.3f} (powinna być bliska 0)')

sr = wydatki.mean() 
sd = wydatki.std()

segmenty = np.where(wydatki > sr + sd, 'WYSOKI', 
           np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

nazwy_seg, ilosc = np.unique(segmenty, return_counts=True)
for n, i in zip(nazwy_seg, ilosc):
    print(f'Segment {n}: {i} klientów')


Wiek - średnia: 33.6, mediana: 33.0
Wydatki - max: 1044.03, min: 116.25
Korelacja wiek-wydatki: -0.120 (powinna być bliska 0)
Segment NISKI: 17 klientów
Segment WYSOKI: 12 klientów
Segment ŚREDNI: 71 klientów
